package com.zw.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOauthRefreshToken<M extends BaseOauthRefreshToken<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppId(java.lang.Integer appId) {
		set("app_id", appId);
	}
	
	public java.lang.Integer getAppId() {
		return getInt("app_id");
	}

	public void setRefreshToken(java.lang.String refreshToken) {
		set("refresh_token", refreshToken);
	}
	
	public java.lang.String getRefreshToken() {
		return getStr("refresh_token");
	}

	public void setExpiresAt(java.util.Date expiresAt) {
		set("expires_at", expiresAt);
	}
	
	public java.util.Date getExpiresAt() {
		return get("expires_at");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

}
