package com.zw.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOauthApp<M extends BaseOauthApp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppCode(java.lang.Integer appCode) {
		set("app_code", appCode);
	}
	
	public java.lang.Integer getAppCode() {
		return getInt("app_code");
	}

	public void setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
	}
	
	public java.lang.String getAppSecret() {
		return getStr("app_secret");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}
	
	public java.lang.String getAppName() {
		return getStr("app_name");
	}

	public void setThumbUrl(java.lang.String thumbUrl) {
		set("thumb_url", thumbUrl);
	}
	
	public java.lang.String getThumbUrl() {
		return getStr("thumb_url");
	}

	public void setAppDesc(java.lang.String appDesc) {
		set("app_desc", appDesc);
	}
	
	public java.lang.String getAppDesc() {
		return getStr("app_desc");
	}

	public void setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
	}
	
	public java.lang.String getContactName() {
		return getStr("contact_name");
	}

	public void setContactEmail(java.lang.String contactEmail) {
		set("contact_email", contactEmail);
	}
	
	public java.lang.String getContactEmail() {
		return getStr("contact_email");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	public java.lang.String getDomain() {
		return getStr("domain");
	}

	public void setRedirectUri(java.lang.String redirectUri) {
		set("redirect_uri", redirectUri);
	}
	
	public java.lang.String getRedirectUri() {
		return getStr("redirect_uri");
	}

	public void setScope(java.lang.String scope) {
		set("scope", scope);
	}
	
	public java.lang.String getScope() {
		return getStr("scope");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreated(java.lang.String created) {
		set("created", created);
	}
	
	public java.lang.String getCreated() {
		return getStr("created");
	}

	public void setUpdated(java.lang.String updated) {
		set("updated", updated);
	}
	
	public java.lang.String getUpdated() {
		return getStr("updated");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
