package com.zw.common.model;

import com.zw.common.model.base.BaseOauthAccessToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OauthAccessToken extends BaseOauthAccessToken<OauthAccessToken> {
	
}
