package com.zw.common.model;

import com.zw.common.model.base.BaseOauthRefreshToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OauthRefreshToken extends BaseOauthRefreshToken<OauthRefreshToken> {
	
}
